config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  resources :questions do
    resources :answers, :except => [:show, :index]
  end
  resources :users

  # resources :sessions, :only => [:new, :create, :destroy]

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  # has_one :vote
  has_many :votes, as: :votable

  # validates :content, :presence => true
  validates_presence_of :content

def vote_count
  total = 0
  self.votes.each do |vote|
    total += vote.vote
  end
  return total
end

default_scope {order('created_at DESC')}
end

app/models/question.rb
class Question < ActiveRecord::Base
#   belongs_to :user
  has_many :answers
#
#   validates :content, :presence => true
#   validates :question, :presence => true
# end

validates_presence_of :content
belongs_to :question
belongs_to :user
has_many :votes, as: :votable

def vote_count
  total = 0
  self.votes.each do |vote|
    total += vote.count
  end
  return total
end

default_scope {order('created_at DESC')}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answer
  has_many :votes, :as => :votable
  # has_one :vote, through: :answer
  # validates_presence_of :user
  # validates_presence_of :email

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # belongs_to :user
  #
  # validates :user, uniqueness: true
  # validates :answer, uniqueness: true
  belongs_to :votable, polymorphic: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def create
    @user = current_user
    if @user == nil
      flash[:danger] = "Log in to submit an answer"
      redirect_to :back
    else
    @question = @user.questions.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save &&  @answer.update(user_id: @user.id)
      redirect_to question_path(@question)
    else
      render :new
    end
  end
end

  def update
    @user = current_user
    if @user == nil
      flash[:danger] = "Log in to vote"
      redirect_to :back
    else
      @question = @user.questions.find(params[:question_id])
      @answer = @question.answers.find(params[:id])
      @vote = Vote.where(user_id: current_user.id, votable_id: @answer.id)
      if @vote.any?
        flash[:danger] = "You cannot vote again"
      # binding.pry
      else
        @answer.votes.create(vote: params[:v][:votes], user_id: current_user.id, votable_id: @answer.id)
      end
      redirect_to question_path(@question)
    end
    # if answer_params[:upvote]
    #   upvote = @answer.upvote
    #   if upvote != nil
    #     upvote = upvote + 1
    #     @answer.update(upvote: upvote)
    #     redirect_to question_path(@question)
    #   else
    #     @answer.update(upvote: 1)
    #     redirect_to question_path(@question)
    #   end
    # elsif answer_params[:downvote]
    #   downvote = @answer.downvote
    #   if downvote != nil
    #     downvote = downvote - 1
    #     @answer.update(downvote: downvote)
    #     redirect_to question_path(@question)
    #   else
    #     @answer.update(downvote: 1)
    #     redirect_to question_path(@question)
    #   end
    # else
    #   redirect_to question_path(@question)
    # end
  end

  def destroy
    @user = current_user
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy

    redirect_to question_path(@question)
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @question = Question.new
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @user = current_user
    if @user
    @question = @user.questions.new(question_params)
    end
    if @user == nil
      flash[:danger] = "Please log in."
      @question = Question.new
      render :new

    elsif @question.save
      redirect_to questions_path
    else
      redirect_to questions_path
    end
  end

  def destroy
    @user = current_user
    @question = @user.questions.find(params[:id])
    @question.answers.each do |answer|
      answer.destroy
    end
    if @question.destroy
      flash[:warning] = "Question deleted"
      redirect_to questions_path
    else
      redirect_to questions_path
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:success] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:danger] = "There was a problem loggin you in."
      redirect_to log_in_path
    end
  end

    def destroy
      session[:user_id] = nil
      flash[:success] = "You've been logged out successfully."
      redirect_to root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    # binding.pry
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      flash[:success] = "user successfully created"
      redirect_to users_path
    elsif user_params[:password] != user_params[:password_confirmation]
      flash[:danger]  = "please try again, passwords did not match"
      redirect_to :back
    else
      flash[:danger] = 'just try again'
      redirect_to :back
    end
  end
  def new
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit %>
  <% end %>

app/views/answers/new.html.erb
<h1>Answer <%= @question.question %></h1>

<%= render 'form' %>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">epicoverflow <i class="fa fa-puzzle-piece fa-1x"></i></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Ask', new_question_path %></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <% if current_user == nil %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/users">Sign up</a></li>
        <li><a href="/log-in">Login</a></li>
      </ul>
      <%else%>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/log-out">log out, <%= current_user.name %> </a>
        </li>
      </ul>
      <%end%>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflowClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render '/layouts/navbar'%>

</head>
<body>
<div class="container">
  <!-- Main component for a primary marketing message or call to action -->

  <div class="jumbotron">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</div> <!-- /container -->
</body>
</html>

app/views/questions/_form.html.erb
<% if current_user != nil %>
  <%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit %>
  <% end %>
 <% else %>
 <div class="alert alert-danger">
Please log in or sign up to ask a question..
 </div>


<% end %>

app/views/questions/_voting.html.erb
<%= form_for object do |v| %>
<%= hidden_field(:v, :votes, :value => '1') %>
<%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-chevron-up pull-right" %>
<% end %>

<%= form_for object do |v| %>
<%= hidden_field(:v, :votes, :value => '-1') %>
<%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-chevron-down pull-right" %>
<% end %>

app/views/questions/index.html.erb
<div class="text-center">


  <%if @questions.any? %>
  <% @questions.each do |question|%>
  <%= link_to question.title, question_path(question) %> <br> by <i><%= question.user.name%></i> <br> <small><%= time_ago_in_words(question.created_at) %></small> ago
  <%end%>
  <%else%>
  <p>
    no questions, ask a question!
  </p>
  <%end%>
  <% if current_user != nil %>
    <p>
      Welcome, <b><%=  current_user.name %></b><br>

      <hr>
    </p>
    <%= link_to 'log out', log_out_path %>
  <% else  %>
  <h2>log in or sign up to ask and/or answer questions! </h2>
  <% end  %>
</div>

app/views/questions/new.html.erb
<h1>Ask a Question</h1>

<%= render 'form' %>

app/views/questions/newQuestion.html.erb
<h1>Ask a Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="text-center">


<%= @question.question %>

<% if current_user == @question.user %>
<%= link_to 'delete question', question_path(@question),
:data => {:confirm => "are you sure?",
  :method => "delete"}%><br>
  <% end %>

<br>
<%= @question.content %> <br>by <%= @question.user.name %> <small><%= time_ago_in_words(@question.created_at) %></small> ago
<% if @question.answers.any? %>
<% @question.answers.each do |answer| %>
   <ul>
     <li>
      <%= answer.vote_count %>
       <%= render 'voting', :object => [@question, answer] %>
       <!-- <%= answer.upvote %>
       <%= form_for [@question, answer] do |v| %>
       <%= v.hidden_field(:upvote, :value => '1') %>
       <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-chevron-up pull-right" %>     <%= answer.downvote %>
       <% end %>   <%= form_for [@question, answer] do |v| %>
       <%= v.hidden_field(:downvote, :value => '1') %>
       <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-chevron-down pull-right" %>
       <% end %> -->
     </li>
     <!-- <li><%= link_to "+", question_answer_path(@question, answer, :upvote => true), :method => :patch %> <%= answer.content %> by <%= answer.user.name %> <small><%= time_ago_in_words(answer.created_at) %></small> ago <% if current_user == answer.user %>
       <%= link_to 'delete answer', question_answer_path(@question, answer),
       :data => {:confirm => "are you sure?",
         :method => "delete"}%><br>
         <% end %></li> -->
   </ul>
<% end %>
<% else %>
<br>
Be the first to answer the question and help out <%= @question.user.name %>

<% end %>
<%= link_to 'answer the question', new_question_answer_path(@question)%>
</div>

app/views/users/_newUser.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "sign up" %>
  <% end %>

app/views/users/index.html.erb
<div class="text-center">
<h1>Users</h1>
<hr>
<h3>sign up:</h3>
  <%=render "users/newUser"%>
</div>